services:
  server:
    build:
      context: ./RecSystem
      dockerfile: Dockerfile
    volumes:
      - ./RecSystem/data:/usr/src/netflix/build/data
    container_name: netflix_server_container
    working_dir: /usr/src/netflix/build

  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./RecSystem/data:/usr/src/netflix/build/data
    container_name: netflix_web_server_container
    working_dir: /usr/src/netflix/web
    depends_on:
      - mongo
    ports:
      - "19844:19844"
  
  mongo:
    image: mongo:8
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  server_data: 
  web_data: 
  mongo_data:
  
        
  # client:
  #   build:
  #     context: ./src/Client
  #     dockerfile: Dockerfile
  #   tty: true
  #   stdin_open: true
  #   init: true
  #   container_name: netflix_client_container
  #   working_dir: /usr/src/netflix-client
